### ISSUE TITLE
Convert license to MIT

### ISSUE THREAD

**Issue by charlie-gallagher** [SDITools/adobeanalyticsr#183]
Hi all, this package is important to many analysts, but it seems like it is no longer being maintained. There are several important updates that need to be made (Jan 1 deadline for OAuth server-to-server, fix the broken OAuth loopback URL, making general improvements to the interfaces). @benrwoodard 's symbolic changing-of-hands pull request #180 has not even been merged yet.

However, no one can (or I guess shouldn't) fork this repo with the current license.

Having personally contributed a significant amount of the code to this project, I have a personal stake in not rewriting this whole thing from scratch, so I would like the new maintainers to consider converting this to an MIT license to encourage community support and progress.

**Comment by braxton-butcher** [comment]
Hi Charlie! Ben's departure did create some difficulties with maintaining the package, but we are currently working to transfer maintainer rights back to Ben to better facilitate updates to the package. The package is likely to be transferred to Ben's personal repo to allow him to continue to maintain the package in the coming days. It is also our understanding that the current license of the package is an MIT license. 

I and others internally at Further have been working specifically to migrate to OAuth Server-to-server with the January 27th date for JWT deprecation in mind, but we would absolutely appreciate any collaboration from others to help make that change! Thank you for your contributions to the package and for your concern over its maintenance.
